version = 0.1

[default.deploy.parameters]
stack_name = "claude-approve-alexa"
resolve_s3 = true
s3_prefix = "claude-approve-alexa"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AlexaClientId=\"YOUR_ALEXA_CLIENT_ID\" AlexaClientSecret=\"YOUR_ALEXA_CLIENT_SECRET\""
image_repositories = []

[default.global.parameters]
region = "us-west-2"
